version: "3.8"

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: appsfactory-weather-mssql
    volumes:
      - mssql-server-data:/var/opt/appsfactory-weather-mssql/data
    restart: unless-stopped
    environment:
      - SA_PASSWORD=appsfactory2021!
      - ACCEPT_EULA=Y
    ports:
      - "1453:1433"
volumes:
  mssql-server-data: